############################################################
# Rest Client API実行ファイル
############################################################

#----------------------------------------------------
# endpoint :
#----------------------------------------------------
###
# @name
GET http://localhost:20000

###
# @name
