services:

  # Rust App(actix-web)
  rust-actix-web:
    container_name: rust-actix-web-${CONTAINER_NAME_SUFFIX}
    build:
      context: .
      dockerfile: infrastructure/rust/Dockerfile
      target: production
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - ${CONTAINER_IP}:${ACTIXT_WEB_PORTS}:8080 # IPとPortを指定
